---

- name: Install DalmatinerDB
  pkg5:
    name: "dalmatinerfe"

# - name: Start DalmatinerDB
#   service:
#     name: svc:/application/dalmatinerdb:default
#     enabled: yes
#     state: started
