---

# - solaris_zone: name={{zone_name}} state=absent

- zfs: name=rpool/zones/{{zone_name}} state=present

- solaris_zone: name={{zone_name}} state=present path=/zones/{{zone_name}} root_password="{{zone_name}}"
    config='set autoboot=true; set ip-type=exclusive; add net; set physical={{zone_name}}; end;'

- solaris_zone: name={{zone_name}} state=installed

- solaris_zone: name={{zone_name}} state=running

- command: zlogin {{zone_name}} ipadm show-addr {{zone_name}}/v4
  register: interface_check
  ignore_errors: True

- command: zlogin {{zone_name}} ipadm create-addr -T dhcp {{zone_name}}/v4
  when: interface_check|failed
