---

# - solaris_zone: name={{zone_name}} state=absent
# - zfs: name=rpool/zones/{{zone_name}} state=absent

- zfs: name=rpool/zones/{{zone_name}} state=present

- command: dladm show-vnic {{zone_name}}
  register: physical_device_check
  ignore_errors: True

- command: dladm create-vnic -l e1000g0 {{zone_name}}
  when: physical_device_check|failed

- solaris_zone: name={{zone_name}} state=present path=/zones/{{zone_name}} root_password="{{zone_name}}"
    config='set autoboot=true; set ip-type=exclusive; add net; set physical={{zone_name}}; end;'

- solaris_zone: name={{zone_name}} state=installed

- template: src=hostname.interface.j2 dest=/zones/{{zone_name}}/root/etc/hostname.{{zone_name}} owner=root group=root mode=0644

- template: src=nodename.j2 dest=/zones/{{zone_name}}/root/etc/nodename owner=root group=root mode=0644

- template: src=dhcpagent.j2 dest=/zones/{{zone_name}}/root/etc/default/dhcpagent owner=root group=root mode=0644

- file: path=/zones/{{zone_name}}/root/etc/dhcp.{{zone_name}} state=touch

- solaris_zone: name={{zone_name}} state=running

- command: zlogin {{zone_name}} ipadm show-addr {{zone_name}}/v4
  register: interface_check
  ignore_errors: True

# - command: zlogin {{zone_name}} ipadm create-addr -T dhcp {{zone_name}}/v4
#   when: interface_check|failed
