- hosts: physical
  roles:
  - { role: omnios-zone, zone_name: ddbfe, net_physical: ddbfe1 }

- hosts: ddbfe

  vars:
    ddb_roles:
    - fe
    ddbfe_idx_pg_backend_host: "{{ hostvars[groups['ddbpg'][0]]['inventory_hostname'] }}"
    ddbfe_db_connection_backend_host: "{{ hostvars[groups['ddbdb'][0]]['inventory_hostname'] }}"
    ddbfe_idx_pg_backend_password: "{{ ddb_pg_password }}"
  vars_files:
  - ../secrets/dalmatiner_fe.yml

  roles:
  - common
  - dalmatinerdb

