---

- include: custom_facts.yml

- copy: src=auto_home dest=/etc/auto_home owner=root mode=644
  notify: refresh autofs

- name: Mount home dataset
  zfs: name="{{zfs_root_pool}}/home" mountpoint="/export/home" state=present
  when: not is_global_zone

- authorized_key: user=root key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- template: src=resolv.conf.j2 dest=/etc/resolv.conf owner=root group=root mode=0644

- name: Use DNS Host resolution
  command: cp /etc/nsswitch.dns /etc/nsswitch.conf

- pkg5_publisher: name=ms.omniti.com sticky=true origin=http://pkg.omniti.com/omniti-ms/
