---

- copy: src=auto_home dest=/etc/auto_home owner=root mode=644

- authorized_key: user=root key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- template: src=resolv.conf.j2 dest=/etc/resolv.conf owner=root group=root mode=0644

- name: Use DNS Host resolution
  command: cp /etc/nsswitch.dns /etc/nsswitch.conf
