---


- solaris_zone: name={{zone_name}} state=absent

- zfs: name=rpool/zones/{{zone_name}} state=absent

- name: dladm delete-vnic {{net_physical}}
  dladm_vnic: name={{net_physical}} link={{net_physical}} state=absent
